# Generated by Django 3.0.3 on 2020-03-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='amt_1000',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owners',
            name='amt_250',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owners',
            name='amt_500',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owners',
            name='amt_can',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owners',
            name='des_can',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='owners',
            name='img_250',
            field=models.ImageField(default=None, upload_to='pics'),
        ),
    ]
