# Generated by Django 3.0.3 on 2020-03-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_auto_20200329_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='img_1000',
            field=models.ImageField(default=None, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='owners',
            name='img_500',
            field=models.ImageField(default=None, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='owners',
            name='img_can',
            field=models.ImageField(default=None, upload_to='pics'),
        ),
    ]
