# Generated by Django 3.0.3 on 2020-03-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_owners_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owners',
            name='crefititate_img1',
        ),
        migrations.RemoveField(
            model_name='owners',
            name='crefititate_img2',
        ),
        migrations.RemoveField(
            model_name='owners',
            name='img_1000',
        ),
        migrations.RemoveField(
            model_name='owners',
            name='img_250',
        ),
        migrations.RemoveField(
            model_name='owners',
            name='img_500',
        ),
        migrations.RemoveField(
            model_name='owners',
            name='img_can',
        ),
        migrations.RemoveField(
            model_name='owners_temp',
            name='crefititate_img1',
        ),
        migrations.RemoveField(
            model_name='owners_temp',
            name='crefititate_img2',
        ),
        migrations.RemoveField(
            model_name='owners_temp',
            name='img_1000',
        ),
        migrations.RemoveField(
            model_name='owners_temp',
            name='img_250',
        ),
        migrations.RemoveField(
            model_name='owners_temp',
            name='img_500',
        ),
        migrations.RemoveField(
            model_name='owners_temp',
            name='img_can',
        ),
        migrations.AlterField(
            model_name='owners_temp',
            name='contact_num1',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='owners_temp',
            name='contact_num2',
            field=models.CharField(default=None, max_length=13),
        ),
    ]
