# Generated by Django 3.0.3 on 2020-03-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0005_auto_20200331_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owners',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='owners_temp',
            name='approved',
        ),
    ]
