from django.db import models

# Create your models here.

class owners(models.Model):
    factory_name=models.CharField(max_length=100)
    contact_num1=models.CharField(max_length=13)
    contact_num2=models.CharField(max_length=13,default=None)
    #crefititate_img1=models.ImageField(upload_to='pics')
    #crefititate_img2=models.ImageField(upload_to='pics',default=None)
    distict=models.CharField(max_length=100)
    area=models.CharField(max_length=150)
    address=desc=models.TextField()
    desc=models.TextField()
    message=models.TextField()
    amt_250=models.BooleanField()
    #img_250=models.ImageField(upload_to='pics',default=None)
    amt_500=models.BooleanField()
    #img_500=models.ImageField(upload_to='pics',default=None)
    amt_1000=models.BooleanField()
    #img_1000=models.ImageField(upload_to='pics',default=None)
    amt_can=models.BooleanField()
    #img_can=models.ImageField(upload_to='pics',default=None)
    des_can=models.TextField(default=None)

class owners_temp(models.Model):
    factory_name=models.CharField(max_length=100)
    contact_num1=models.CharField(max_length=13)
    contact_num2=models.CharField(max_length=13,default=None)
    #crefititate_img1=models.ImageField(upload_to='pics')
    #crefititate_img2=models.ImageField(upload_to='pics',default=None)
    distict=models.CharField(max_length=100)
    area=models.CharField(max_length=150)
    address=desc=models.TextField()
    desc=models.TextField()
    message=models.TextField()
    amt_250=models.BooleanField()
    #img_250=models.ImageField(upload_to='pics',default=None)
    amt_500=models.BooleanField()
    #img_500=models.ImageField(upload_to='pics',default=None)
    amt_1000=models.BooleanField()
    #img_1000=models.ImageField(upload_to='pics',default=None)
    amt_can=models.BooleanField()
    #img_can=models.ImageField(upload_to='pics',default=None)
    des_can=models.TextField()
